import Head from 'next/head';
import Entrance from '../src/components/Entrance';
import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';
import LottieLoader from '../src/components/LottiePenguin';
import Footer from '../src/components/Footer';
import { INTRO_COVER_EXIT_DELAY } from '/src/util/timings';


const motionIntroCoverContainer = {
  show: {
    x: 0,
    opacity: 1,
  },
  exit: {
    x: "110vw",
    transition: {
      ease: "easeInOut",
      duration: INTRO_COVER_EXIT_DELAY,
    }
  }
}

export default function Home() {
  const [finishIntro, setFinishIntro] = useState(false);

  return (
    <div>
      <Head>
        <title>Julian's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <AnimatePresence>
          {!finishIntro &&
            <motion.div
              className="h-screen w-screen flex items-center justify-center bg-gray-500 absolute z-50"
              key="intro-cover"
              variants={motionIntroCoverContainer}
              initial="show"
              animate="show"
              exit="exit"
              onAnimationComplete={() => {
                setTimeout(() => setFinishIntro(true), INTRO_COVER_EXIT_DELAY * 1000 )}
              }
            >
              <LottieLoader />
            </motion.div>
          }
        </AnimatePresence>
        
        {
          finishIntro &&
          <Entrance />
        }
      </main>

      {/* <Footer /> */}
    </div>
  )
}
